export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_UP_EMAIL_CHANGED = "SIGN_UP_EMAIL_CHANGED";
export const SIGN_UP_PASSWORD_CHANGED = "SIGN_UP_PASSWORD_CHANGED";
export const SIGN_UP_PASSWORD_CONFIRM_CHANGED =
  "SIGN_UP_PASSWORD_CONFIRM_CHANGED";
